# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logview < Formula
  desc "Terminal log viewer with real-time search and filtering"
  homepage "https://github.com/Miragefl/logview"
  version "0.12.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miragefl/logview/releases/download/v0.12.14/logview_darwin_amd64.tar.gz"
      sha256 "413916720d381aeac39d2b7556fb3e1d19e7a7912d79dc1e019fa2e3bc538fb2"

      define_method(:install) do
        bin.install "logview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miragefl/logview/releases/download/v0.12.14/logview_darwin_arm64.tar.gz"
      sha256 "4ba84841af558d1d9d0f6fad2df003f7a3de1de8d77eadf5b1e96324ac1e46ca"

      define_method(:install) do
        bin.install "logview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miragefl/logview/releases/download/v0.12.14/logview_linux_amd64.tar.gz"
      sha256 "f5b94ebdc7787cc360283f2ca6a5a19813bd0d214ace0fe4fc74f174f2ef7308"
      define_method(:install) do
        bin.install "logview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miragefl/logview/releases/download/v0.12.14/logview_linux_arm64.tar.gz"
      sha256 "68f3ecde2730da260eadd1c80e56e0d7aaa685ffff21e761d5f0d5c39d92e6b6"
      define_method(:install) do
        bin.install "logview"
      end
    end
  end

  test do
    system "#{bin}/logview --help"
  end
end
