# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logview < Formula
  desc "Terminal log viewer with real-time search and filtering"
  homepage "https://github.com/Miragefl/logview"
  version "0.17.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miragefl/logview/releases/download/v0.17.0/logview_darwin_amd64.tar.gz"
      sha256 "f0131b0e401240fd9d21fc91442fb3b5e50ec70fe99d3af1f039065ade88618c"

      define_method(:install) do
        bin.install "logview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miragefl/logview/releases/download/v0.17.0/logview_darwin_arm64.tar.gz"
      sha256 "6fa0122ed685a352ffc816e388eecc2e7317136884e088d1f11d08b67cba2d88"

      define_method(:install) do
        bin.install "logview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miragefl/logview/releases/download/v0.17.0/logview_linux_amd64.tar.gz"
      sha256 "e09febb84001885e7e507ad4b11c474680c19c9c6eec24aa1426ed1d264f2782"
      define_method(:install) do
        bin.install "logview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miragefl/logview/releases/download/v0.17.0/logview_linux_arm64.tar.gz"
      sha256 "c6b5d5490d585800ed61aa05f178af2101c789681e4b42526738759aa38467cc"
      define_method(:install) do
        bin.install "logview"
      end
    end
  end

  test do
    system "#{bin}/logview --help"
  end
end
